export const SUBMISSION_SELECT = "SUBMISSION_SELECT"
export const SUBMISSION_CHANGE_ALL = "SUBMISSION_CHANGE_ALL"
export const SUBMISSION_RECEIVE_CLONE_PROGRESS = "SUBMISSION_RECEIVE_CLONE_PROGRESS"
export const SUBMISSION_SET_CLONE_PATH = "SUBMISSION_SET_CLONE_PATH"
