export const SUBMISSION_SELECT = "SUBMISSION_SELECT"
export const SUBMISSION_SELECT_ALL = "SUBMISSION_SELECT_ALL"
export const SUBMISSION_SET_PROGRESS = "SUBMISSION_SET_PROGRESS"
export const SUBMISSION_SET_CLONE_PATH = "SUBMISSION_SET_CLONE_PATH"
