#!/bin/sh

set -x

echo "Downloading Certificate from $KEY_LINK"
curl -o ./classroom-assistant-cert.p12 -k $KEY_LINK

echo "Importing Certificate!"
KEY_CHAIN=mac-build.keychain
security create-keychain -p travis $KEY_CHAIN
security import classroom-assistant-cert.p12 -k $KEY_CHAIN -P $KEY_PASSWORD -T /usr/bin/codesign

echo "Unlocking Certificate"
security list-keychain -s $KEY_CHAIN
security unlock-keychain -p travis $KEY_CHAIN
security set-keychain-settings -t 3600 -u $KEY_CHAIN

security default-keychain -s $KEY_CHAIN

# set key partition list to avoid UI permission popup that causes hanging at CI
security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k travis $KEY_CHAIN
