export const ASSIGNMENT_SET_TITLE = "ASSIGNMENT_SET_TITLE"
export const ASSIGNMENT_SET_TYPE = "ASSIGNMENT_SET_TYPE"
export const ASSIGNMENT_REQUEST_INFO = "ASSIGNMENT_REQUEST_INFO"
export const ASSIGNMENT_RECEIVE_INFO = "ASSIGNMENT_RECEIVE_INFO"
